=== greenscar/scripts/buildforge/interface.dtd
<!ELEMENT PROJECT_INTERFACE (template*,interface,command+,bomformat+)>
<!ATTLIST PROJECT_INTERFACE IFTYPE CDATA #REQUIRED>
<!ATTLIST PROJECT_INTERFACE INSTANCE CDATA #REQUIRED>
<!ELEMENT template (env+)>
<!ELEMENT interface (setenv*,adduser*,relate*,run+,adduser*,relate*,ontempenv*,onstep*,onproject*,setenv*,adduser*,relate*,ontempenv*,onstep*,onproject*)>
<!ATTLIST interface name CDATA #IMPLIED>
<!ELEMENT command (execute*,integrate*,resultsblock+)>
<!ATTLIST command name CDATA #REQUIRED>
<!ATTLIST command type (exec | conjoined | parallel) #IMPLIED>
<!ELEMENT bomformat (section+)>
<!ATTLIST bomformat category CDATA #REQUIRED>
<!ATTLIST bomformat title CDATA #REQUIRED>
<!ELEMENT env EMPTY>
<!ATTLIST env name CDATA #REQUIRED>
<!ATTLIST env value CDATA #REQUIRED>
<!ELEMENT setenv EMPTY>
<!ATTLIST setenv group CDATA #IMPLIED>
<!ATTLIST setenv name CDATA #REQUIRED>
<!ATTLIST setenv value CDATA #REQUIRED>
<!ATTLIST setenv type CDATA #IMPLIED>
<!ATTLIST setenv eval CDATA #IMPLIED>
<!ATTLIST setenv condition CDATA #IMPLIED>
<!ELEMENT run EMPTY>
<!ATTLIST run command CDATA #REQUIRED>
<!ATTLIST run params CDATA #REQUIRED>
<!ATTLIST run server CDATA #REQUIRED>
<!ATTLIST run dir CDATA #REQUIRED>
<!ATTLIST run timeout CDATA #IMPLIED>
<!ATTLIST run condition CDATA #IMPLIED>
<!ATTLIST run mode (exec | conjoined | parallel) #IMPLIED>
<!ELEMENT ontempenv (step+,setenv*)>
<!ATTLIST ontempenv name CDATA #REQUIRED>
<!ATTLIST ontempenv state (empty | hastext | true | false) #REQUIRED>
<!ELEMENT onproject (notify+)>
<!ATTLIST onproject result (PASS|FAIL|pass|fail) #REQUIRED>
<!ELEMENT onstep (setenv*)>
<!ATTLIST onstep result (PASS|FAIL|pass|fail) #REQUIRED>
<!ELEMENT execute (#PCDATA)>
<!ELEMENT integrate (#PCDATA)>
<!ELEMENT resultsblock (match*,setenv*,resultsblock*,match*,setenv*,resultsblock*)>
<!ATTLIST resultsblock beginpattern CDATA #IMPLIED>
<!ATTLIST resultsblock endpattern CDATA #IMPLIED>
<!ELEMENT section (field+)>
<!ATTLIST section name CDATA #REQUIRED>
<!ATTLIST section parent CDATA #IMPLIED>
<!ATTLIST section expandable (true|false) #IMPLIED>
<!ELEMENT step EMPTY>
<!ATTLIST step result (FAIL|PASS|fail|pass) #REQUIRED>
<!ELEMENT notify EMPTY>
<!ATTLIST notify group CDATA #REQUIRED>
<!ATTLIST notify subject CDATA #REQUIRED>
<!ATTLIST notify message CDATA #REQUIRED>
<!ELEMENT match (bom*,adduser*,relate*,setenv*,run*,bom*,adduser*,relate*,setenv*,run*)>
<!ATTLIST match pattern CDATA #REQUIRED>
<!ELEMENT field EMPTY>
<!ATTLIST field name CDATA #REQUIRED>
<!ATTLIST field text CDATA #IMPLIED>
<!ATTLIST field order CDATA #IMPLIED>
<!ATTLIST field title CDATA #IMPLIED>
<!ELEMENT bom (field+)>
<!ATTLIST bom category CDATA #REQUIRED>
<!ATTLIST bom section CDATA #REQUIRED>
<!ATTLIST bom condition CDATA #IMPLIED>
<!ELEMENT adduser EMPTY>
<!ATTLIST adduser group CDATA #REQUIRED>
<!ATTLIST adduser user CDATA #REQUIRED>
<!ATTLIST adduser condition CDATA #IMPLIED>
<!ELEMENT relate EMPTY>
<!ATTLIST relate artifact CDATA #REQUIRED>
<!ATTLIST relate user CDATA #REQUIRED>

=== greenscar/scripts/buildforge/condition_test.xml
<!DOCTYPE PROJECT_INTERFACE SYSTEM "interface.dtd">
<PROJECT_INTERFACE IFTYPE="Source" INSTANCE="7.02">
   <template>
      <env name="BF_SERVER"         value="required"/>
      <env name="DO_REBASE"         value="required"/>
   </template>
   
   <interface>
      <run command="set_test_lvl" params="SSP_73.2.x.0_SPE_LOCAL" server="$BF_SERVER" dir="/" timeout="120" condition="true('$DO_REBASE' eq 'YES')"/>
      
      <run command="autobl" params="" server="$BF_SERVER" dir="/" timeout="300" condition=""/>
      
	   <setenv name="JAMES" value="stuff" type="temp"/>
		<run command="test" params="PHIL" server="$BF_SERVER" dir="/" timeout="360" condition="isempty($PHIL)"/>
		<run command="test" params="JAMES" server="$BF_SERVER" dir="/" timeout="360" condition="hastext($JAMES)"/>
   </interface>
   
	<command name="test">
		<execute>
		echo $1
		</execute>
		<resultsblock/>
	</command>

   
   <command name="set_test_lvl">
      <execute>
         echo '$1'
      </execute>
      <resultsblock>
         <match pattern="(LOCAL)">
            <setenv name="DO_REBASE" value="NO" type="temp"/>
         </match>
      </resultsblock>
   </command>
   
   <command name="autobl">
      <execute>
         print "LOCAL - NO REBASE NEEDED"
      </execute>
      <resultsblock>
         <match pattern="^(LOCAL .+)">
            <run command="test2" params="$1" server="$BF_SERVER" dir="/" timeout="600"/>
         </match>
         <match pattern="(LOCAL .+)">
            <setenv name="OLDBL" value="$2" type="temp"/>
            <setenv name="testlvl" value="LOCAL" type="temp"/>
         </match>
      </resultsblock>
   </command>
   
</PROJECT_INTERFACE>

=== greenscar/scripts/buildforge/check_coding_standards.xml
<!DOCTYPE PROJECT_INTERFACE SYSTEM "interface.dtd">
<PROJECT_INTERFACE IFTYPE="Source" INSTANCE="7.02">
   <template>
      <!-- Template section, these are parsed out of the final xml and used to populate an 
      existing environment group if an instance of this interface is linked with a project.
      However, use the list below to help identify the variables needed to run this interface
      if you are integrating it during a regular BuildForge step.
      -->
      <env name="CS_WORKING_DIR" value="MyProject\MyDirectory"/>
      <env name="CS_JAR" value="lib\checkstyle-all-4.2.jar"/>
      <env name="CS_CHECK_DIR" value="src"/>
      <env name="CS_CONF_FILE" value="checkstyle.xml"/>
      <env name="CS_EXTRA_FLAGS" value=""/>
   </template>
   
   <!-- parse a source directory and report on any checkstyle violations -->
   <interface>
      <run command="check_errors" params="$CS_JAR $CS_WORKING_DIR $CS_CHECK_DIR $CS_CONF_FILE $CS_EXTRA_FLAGS" server="$BF_SERVER" dir="/$BF_PROJECTNAME_PHYS/$BF_TAG" timeout="360"/>
      <ontempenv name="Errors" state="hastext">
         <!-- No checkstyle error, pass the build, default behaviour is fail -->
         <step result="FAIL"/>
      </ontempenv>
   </interface>
   
   <command name="check_errors">
      <execute>
         cd
         cd $BF_TAG\$VOB\$MODULE
         java -jar $1 -r $3 -c $4 $5
      </execute>
      <resultsblock>
         <match pattern="^(.*?):(.*?):(.*?): (.*?)$">
            <bom category="Checkstyle" section="checkstyle">
               <field name="File" text="$1"/>
               <field name="Line" text="$2"/>
               <field name="Column" text="$3"/>
               <field name="Message" text="$4"/>
            </bom>
            <setenv name="Errors" value="$1: $4" type="temp append\n"/>
         </match>
      </resultsblock>
   </command>
   
   <bomformat category="Checkstyle" title="Java Checkstyle Results">
      <section name="checkstyle">
         <field order="1" name="File"/>
         <field order="2" name="Line"/>
         <field order="3" name="Column"/>
         <field order="4" name="Message"/>
      </section>
   </bomformat>
</PROJECT_INTERFACE>

=== greenscar/scripts/buildforge/system.out.print_cleanup_STP.xml
<!DOCTYPE PROJECT_INTERFACE SYSTEM "interface.dtd">
<PROJECT_INTERFACE IFTYPE="Source" INSTANCE="7.02">
   <template>
      <!-- Template section, these are parsed out of the final xml and used to populate an 
      existing environment group if an instance of this interface is linked with a project.
      However, use the list below to help identify the variables needed to run this interface
      if you are integrating it during a regular BuildForge step.
      -->
      <env name="VIEW_NAME"        value="view"/>
      <env name="ACTION"      value="search"/>
      <env name="BF_SERVER"   value="iedaau020_wasadmin"/>
      <env name="PBAD_DIR"    value="pbad_dir"/>
      <env name="APP"         value="STP"/>
   </template>
   
   <interface>
   
      <run command="clean_system_outs" params="$APP $VIEW_NAME $ACTION" server="$BF_SERVER" dir="${PBAD_DIR}/scripts/perl" timeout="600"/>
   </interface>
   
   <command name="clean_system_outs">
      <execute>
         /usr/bin/perl system_out_clean.pl --stream=$2 --action=$3
      </execute>
      <resultsblock>
         <match pattern="((^\s)*)">
            <bom category="STP System.out.printlns" section="Files">
               <field name="file" text="$_"/>
            </bom>
         </match>
      </resultsblock>
   </command>   
   
   <bomformat category="STP System.out.printlns" title="System.out.printlns">
      <section name="Files" expandable="true">
         <field order="1" name="file" title="Files"/>         
      </section>
   </bomformat>
</PROJECT_INTERFACE>

=== greenscar/scripts/buildforge/ClearCaseByBaselineActivities.xml
<?xml version="1.0"?>
<!-- (c) Copyright by IBM Corp. and other(s) [2003], 2007 All Rights Reserved. -->
<!DOCTYPE PROJECT_INTERFACE SYSTEM "interface.dtd" >
<PROJECT_INTERFACE IFTYPE="Source" INSTANCE="7.021">
	<template>
		<!-- Template section, these are parsed out of the final xml and used to populate an 
		existing environment group if an instance of this interface is linked with a project.
		However, use the list below to help identify the variables needed to run this interface
		if you are integrating it during a regular BuildForge step.
		-->
		<env name="CurDate" value=".date %d-%b-%y.%H:%M:%S" />
		<env name="LAST_RUN" value="1-Jan-05.00:00:00" />
		<env name="BASELINE" value="BUILD_1"/>
		<env name="VIEW" value="my_adaptor_view" />
		<env name="VOB_PATH" value="\AdaptorVob" />
		<env name="PROJECT_VOB" value="\ProjectVob" />
		<env name="CCSERVER" value="BFServerName" />
		<env name="UNIXCLIENT" value="0"/>
	</template>
	<!-- The 'ByBaseline' entry point will create a new baseline inside your source, and will then diff between the 
	newly crated baseline, and the baseline created during the previous build of the project -->
	<interface>
		<!-- The internal variable 'Changing' is used to store an email template that we will dynamically generate -->
		<setenv name="Changing" value="Source Changes for this Build:\n" type="temp"/>
		<!-- Set some platform specific information -->
		<setenv name="CdCommand" value="cd /view" type="temp" condition="true($UNIXCLIENT==1)"/>
		<setenv name="CdCommand" value="pushd \\view" type="temp" condition="true($UNIXCLIENT==0)"/>
		<setenv name="DirSep" value="/" type="temp" condition="true($UNIXCLIENT==1)"/>
		<setenv name="DirSep" value="\" type="temp" condition="true($UNIXCLIENT==0)"/>
		<!-- cc_baseline is detailed below, but is basically a quick command to create a new baseline. -->
		<run command="cc_baseline" params="$VIEW $VOB_PATH" server="$CCSERVER" dir="/" timeout="360"/>
		<!-- cc_baselineactivities is detailed below but is basically the entry point into the command set to gather change info" -->
		<run command="cc_baselineactivities" params="$BASELINE $VIEW $PROJECT_VOB" server="$CCSERVER" dir="/" timeout="360"/>
		<!-- Here we test to see if we have any changes, 'Changes' should have some data if a change was found -->
		<ontempenv name="Changes" state="empty">
			<!-- No changes, fail the build, default behaviour is pass -->
			<step result="FAIL"/>
		</ontempenv>
		<!-- If we found changes (not failing step), then update our environment for the next run -->
		<onstep result="pass">
			<setenv group="[ADAPTOR]" name="BASELINE" value="$BF_TAG"/>
		</onstep>
		<!-- Set some notifications for when the build completes -->
		<onproject result="fail">
			<notify group="MyChangers" subject="Build $BF_TAG ($CurDate) Failed." message="${Changing}${Changes}"/>
		</onproject>
		<onproject result="pass">
			<notify group="MyChangers" subject="Build $BF_TAG ($CurDate) Passed." message="${Changing}${Changes}"/>
		</onproject>
	</interface>
	<!-- this command creates a baseline named using the Build Tag for the view -->
	<command name="cc_baseline">
		<execute>
cleartool startview $1
$CdCommand${DirSep}$1 &amp;&amp; cleartool mkbl -c "Build $BF_TAG" -full -view $1 $BF_TAG
		</execute>
		<resultsblock/>
	</command>
	<!-- This command lists the activities that occurred between two baselines, 
		it then calls cc_actdescribe to gather further details about the activities -->
	<command name="cc_baselineactivities">
		<execute>
$CdCommand${DirSep}$2 &amp;&amp; cleartool diffbl -act $1@$3 $BF_TAG@$3
		</execute>
		<resultsblock>
			<match pattern="^[->]>\s+([^\s].*?)\s.*$">
				<run command="cc_actdescribe" params="$VIEW $1" server="$CCSERVER" dir="/" timeout="360"/>
			</match>
		</resultsblock>
	</command>
	<!-- This command gathers details about an activity and logs pertinent information to the BuildForge BOM -->
	<command name="cc_actdescribe">
		<execute>
$CdCommand${DirSep}$1 &amp;&amp; cleartool lsact -l $2
		</execute>
		<resultsblock>
			<!-- look for something resempling an activity identifier -->
			<match pattern="^activity\s&quot;(.*?)&quot;$">
				<bom category="Source" section="activities">
					<field name="id" text="$1"/>
				</bom>
			</match>
			<!-- look for an activity owner -->
			<match pattern="owner:\s(.*?\\|)(.*?)$">
				<bom category="Source" section="activities">
					<field name="owner" text="${1}${2}"/>
				</bom>
				<!-- add the user to our list of people who contributed changes to this build -->
				<adduser group="MyChangers" user="$2"/>
			</match>
			<!-- look for some stream information -->
			<match pattern="stream:\s(.*?)$">
				<bom category="Source" section="activities">
					<field name="stream" text="$1"/>
				</bom>
			</match>
			<!-- See if we get a title for this activity -->
			<match pattern="title:\s(.*?)$">
				<bom category="Source" section="activities">
					<field name="title" text="$1"/>
				</bom>
			</match>
			<!-- This identifies any file/directory changes within the activity -->
			<match pattern="^\s+([\\/].*?)\@\@(.*?\d)$">
				<bom category="Source" section="changeset">
					<field name="version" text="$1@@$2"/>
				</bom>
				<!-- add the information to our email template -->
				<setenv name="Changes" value="$1\@\@$2" type="temp append\n"/>
				<!-- and then run cc_diff to log the differences associated with this changed object -->
				<run command="cc_diff" params="$VIEW $1 $2" server="$CCSERVER" dir="/" timeout="360"/>
			</match>
			<!-- Log clearquest info if we get a record -->
			<match pattern="clearquest record id:\s(.*?)$">
				<bom category="Source" section="clearquestinfo">
					<field name="cqid" text="$1"/>
				</bom>
			</match>
			<match pattern="clearquest record State:\s(.*?)$">
				<bom category="Source" section="clearquestinfo">
					<field name="cqstate" text="$1"/>
				</bom>
			</match>
		</resultsblock>
	</command>
	<!-- The cc_diff command does a generic clearcase diff, logging the full output of the diff in the BuildForge BOM -->
	<command name="cc_diff">
		<execute>
$CdCommand${DirSep}$1 &amp;&amp; cleartool diff -pred -diff_format &quot;$2@@$3&quot;
		</execute>
		<resultsblock>
			<match pattern=".+">
				<bom category="Source" section="diff">
					<field name="diff" text="$_"/>
				</bom>
			</match>
		</resultsblock>
	</command>
	<!-- The bomformat sets up the BuildForge BOM display for the information we gather during this interface execution -->
	<!-- A category is a top level expandable item -->
	<bomformat category="Source" title="Source Changes">
		<!-- A section defines the columns for blocks of information, a new row of information is added 
			each time the last field (by order number) in a block is populated with new information -->
		<section name="changes">
			<field order="1" name="file" title="File/Dir Name"/>
			<field order="2" name="version" title="Version"/>
			<field order="3" name="date" title="Date"/>
			<field order="4" name="user" title="User"/>
			<field order="5" name="comment" title="Comment"/>
		</section>
		<section name="activities">
			<field order="1" name="id" title="Activity"/>
			<field order="2" name="owner" title="Owner"/>
			<field order="3" name="stream" title="Stream"/>
			<field order="4" name="title" title="Title"/>
		</section>
		<section name="changeset">
			<field order="1" name="version" title="Change set version"/>
		</section>
		<section name="clearquestinfo">
			<field order="1" name="cqid" title="ClearQuest record ID"/>
			<field order="2" name="cqstate" title="ClearQuest record state"/>
		</section>
		<section name="diff">
			<field name="diff" title="Change Details"/>
		</section>
	</bomformat>
</PROJECT_INTERFACE>

=== greenscar/scripts/buildforge/phurnace.xml
<?xml version="1.0"?>

<!-- (c) Copyright by Phurnace Software, 2008 All Rights Reserved. -->

<!DOCTYPE PROJECT_INTERFACE SYSTEM "interface.dtd">
<PROJECT_INTERFACE IFTYPE="Source" INSTANCE="7.02">
<template>
        <!-- Environment initialization
            PH_OUTPUT      Location of Phurnace output.txt file
        -->
        <env name="PH_OUTPUT" value="$PHURNACEDIR\output.txt"/>
    </template>
<interface>
        <run command="add_ph_bom" params="D0000010 $BF_TAG" dir="/" timeout="360"/>
</interface>
<command name="add_ph_bom">
   <execute>
      cat $PHOUTPUT | grep Log4j
   </execute>
   <resultsblock>
      <!-- Isolate important information from Phurnace output log -->
      <!-- works for websphere <match pattern="Log4jExporter.java\:84\) - (.+?)\s(.+?)$"> -->
      <match pattern="Log4jExporter\ -\ (.+)\s{5}(installed)\s{5}(.+)\s{5}(.+)$">
         <bom category="PhurnaceInstall" section="install">
             <field name="mbean" text="$1"/>
             <field name="result" text="$2"/>
             <field name="attribute" text="$3"/>
             <field name="newvalue" text="$4"/>
         </bom>
      </match>
      <match pattern="Log4jExporter\ -\ (.+)\s{5}(updated)\s{5}(.+)\s{5}(.+)\s{5}(.+)\s{5}(.+)$">
         <bom category="PhurnaceUpdate" section="update">
             <field name="mbean" text="$1"/>
             <field name="operation" text="$2"/>
             <field name="type" text="$3"/>
             <field name="attribute" text="$4"/>
             <field name="prevvalue" text="$5"/>
             <field name="newvalue" text="$6"/>
         </bom>
      </match>
   </resultsblock>
</command>

<!-- Reports a brief summary of the mbean changes that are included in this deployment. -->

<bomformat category="PhurnaceInstall" title="Phurnace Install">
   <section name="install">
       <field order="1" name="mbean" title="MBean"/>
       <field order="2" name="result" title="Result"/>
       <field order="3" name="attribute" title="Attribute"/>
       <field order="4" name="newvalue" title="NewValue"/>
   </section>
</bomformat>
<bomformat category="PhurnaceUpdate" title="Phurnace Updates">
   <section name="update">
       <field order="1" name="mbean" title="MBean"/>
       <field order="2" name="operation" title="Operation"/>
       <field order="3" name="type" title="Type"/>
       <field order="4" name="attribute" title="Attribute"/>
       <field order="5" name="prevvalue" title="Prev Value"/>
       <field order="6" name="newvalue" title="New Value"/>
   </section>
</bomformat>
</PROJECT_INTERFACE>

=== greenscar/scripts/buildforge/ClearCaseByBaselineVersions.xml
<?xml version="1.0"?>
<!-- (c) Copyright by IBM Corp. and other(s) [2003], 2007 All Rights Reserved. -->
<!DOCTYPE PROJECT_INTERFACE SYSTEM "interface.dtd">
<PROJECT_INTERFACE IFTYPE="Source" INSTANCE="7.021">
	<template>
		<!-- Template section, these are parsed out of the final xml and used to populate an 
		existing environment group if an instance of this interface is linked with a project.
		However, use the list below to help identify the variables needed to run this interface
		if you are integrating it during a regular BuildForge step.
		-->
		<env name="CurDate" value=".date %d-%b-%y.%H:%M:%S" />
		<env name="LAST_RUN" value="1-Jan-05.00:00:00" />
		<env name="LABEL" value="BUILD_1"/>
		<env name="BASELINE" value="BUILD_1"/>
		<env name="VIEW" value="my_adaptor_view" />
		<env name="VOB_PATH" value="\AdaptorVob" />
		<env name="PROJECT_VOB" value="\ProjectVob" />
		<env name="CCSERVER" value="BFServerName" />
		<env name="UNIXCLIENT" value="0"/>
		<env name="_CHAR_NATIVE" value="1" />
	</template>
	<!-- The 'ByBaseline' entry point will create a new baseline inside your source, and will then diff between the 
	newly crated baseline, and the baseline created during the previous build of the project -->
	<interface>
		<!-- The internal variable 'Changing' is used to store an email template that we will dynamically generate -->
		<setenv name="Changing" value="Source Changes for this Build:\n" type="temp"/>
		<!-- Set some platform specific information -->
		<setenv name="CdCommand" value="cd /view" type="temp" condition="true($UNIXCLIENT==1)"/>
		<setenv name="CdCommand" value="pushd \\view" type="temp" condition="true($UNIXCLIENT==0)"/>
		<setenv name="DirSep" value="/" type="temp" condition="true($UNIXCLIENT==1)"/>
		<setenv name="DirSep" value="\" type="temp" condition="true($UNIXCLIENT==0)"/>
		<setenv name="ExpansionVar" value="%" type="temp" condition="true($UNIXCLIENT==1)"/>
		<setenv name="ExpansionVar" value="%%" type="temp" condition="true($UNIXCLIENT==0)"/>
		<!-- cc_baseline is detailed below, but is basically a quick command to create a new baseline. -->
		<run command="cc_baseline" params="$VIEW $VOB_PATH" server="$CCSERVER" dir="/" timeout="360"/>
		<run command="cc_baselineversions" params="$BASELINE $VIEW $PROJECT_VOB" server="$CCSERVER" dir="/" timeout="360"/>
		<!-- Here we test to see if we have any changes, 'Changes' should have some data if a change was found -->
		<ontempenv name="Changes" state="empty">
			<!-- No changes, fail the build, default behaviour is pass -->
			<step result="FAIL"/>
		</ontempenv>
		<!-- If we found changes (not failing step), then update our environment for the next run -->
		<onstep result="pass">
			<setenv group="[ADAPTOR]" name="LABEL" value="$BF_TAG"/>
		</onstep>
		<!-- Set some notifications for when the build completes -->
		<onproject result="fail">
			<notify group="MyChangers" subject="Build $BF_TAG ($CurDate) Failed." message="${Changing}${Changes}"/>
		</onproject>
		<onproject result="pass">
			<notify group="MyChangers" subject="Build $BF_TAG ($CurDate) Passed." message="${Changing}${Changes}"/>
		</onproject>
	</interface>
	<!-- this command creates a baseline named using the Build Tag for the view -->
	<command name="cc_baseline">
		<execute>
cleartool startview $1
$CdCommand${DirSep}$1 &amp;&amp; cleartool mkbl -c "Build $BF_TAG" -full -view $1 $BF_TAG
		</execute>
		<resultsblock/>
	</command>
	<!-- This command runs a diff against two baselines looking for file changes, 
		then calls a command to gather details about those changes -->
	<command name="cc_baselineversions">
		<execute>
$CdCommand${DirSep}$2 &amp;&amp; cleartool diffbl -ver $1@$3 $BF_TAG@$3
		</execute>
		<resultsblock>
			<match pattern="^.*?\s([^\s].*?)\@\@(.*?)$">
				<run command="cc_describe" params="$VIEW $1 $2" server="$CCSERVER" dir="/" timeout="360"/>
			</match>
		</resultsblock>
	</command>
	<!-- This command gets some details about a particular object version -->
	<command name="cc_describe">
		<execute>
$CdCommand${DirSep}$1 &amp;&amp; cleartool desc -fmt "${ExpansionVar}En:${ExpansionVar}Vn:${ExpansionVar}Nd:${ExpansionVar}u:${ExpansionVar}c" $2@@$3
		</execute>
		<resultsblock>
			<!-- Foreach match of our output, we log information to the BOM, and then generate
				some diff output using the cc_diff command -->
			<match pattern="^(.*?):(.*?):(.*?):(.*?):(.*?)$">
				<bom category="Source" section="changes">
					<field name="file" text="$1"/>
					<field name="version" text="$2"/>
					<field name="date" text="$3"/>
					<field name="user" text="$4"/>
					<field name="comment" text="$5"/>
				</bom>
				<run command="cc_diff" params="$VIEW $1 $2" server="$CCSERVER" dir="/" timeout="360"/>
				<!-- We also add the user who created this version to our list of changers for this build, and
					we further populate our email template with user and file information -->
				<adduser group="MyChangers" user="$4"/>
				<setenv name="Changes" value="$4 - $1" type="temp append\n"/>
			</match>
		</resultsblock>
	</command>
	<!-- The cc_diff command does a generic clearcase diff, logging the full output of the diff in the BuildForge BOM -->
	<command name="cc_diff">
		<execute>
$CdCommand${DirSep}$1 &amp;&amp; cleartool diff -pred -diff_format &quot;$2@@$3&quot;
		</execute>
		<resultsblock>
			<match pattern=".+">
				<bom category="Source" section="diff">
					<field name="diff" text="$_"/>
				</bom>
			</match>
		</resultsblock>
	</command>
	<!-- The bomformat sets up the BuildForge BOM display for the information we gather during this interface execution -->
	<!-- A category is a top level expandable item -->
	<bomformat category="Source" title="Source Changes">
		<!-- A section defines the columns for blocks of information, a new row of information is added 
			each time the last field (by order number) in a block is populated with new information -->
		<section name="changes">
			<field order="1" name="file" title="File/Dir Name"/>
			<field order="2" name="version" title="Version"/>
			<field order="3" name="date" title="Date"/>
			<field order="4" name="user" title="User"/>
			<field order="5" name="comment" title="Comment"/>
		</section>
		<section name="diff">
			<field name="diff" title="Change Details"/>
		</section>
	</bomformat>
</PROJECT_INTERFACE>

=== greenscar/scripts/buildforge/autobaseline.xml
<!DOCTYPE PROJECT_INTERFACE SYSTEM "interface.dtd">
<PROJECT_INTERFACE IFTYPE="Source" INSTANCE="7.02">
   <template>
      <!-- Template section, these are parsed out of the final xml and used to populate an 
      existing environment group if an instance of this interface is linked with a project.
      However, use the list below to help identify the variables needed to run this interface
      if you are integrating it during a regular BuildForge step.
      -->
      <env name="VIEW_NAME"        value="view"/>
      <env name="BF_SERVER"   value="iedaau020_wasadmin"/>
      
   </template>
   
   <interface>
      <run command="set_app_rel_src" params="$VIEW_NAME" server="${BF_SERVER}" dir="/" timeout="360"/>
      <run command="set_prev_source_stream" params="$PREV_SOURCE_STREAM" server="${BF_SERVER}" dir="/" timeout="360"/>
      <!--
      <run command="clean_system_outs" params="$APP $VIEW $ACTION" server="$BF_SERVER" dir="${PBAD_DIR}/scripts/perl" timeout="600"/>
      -->
      <run command="printit" params="$PREV_SOURCE_STREAM" server="${BF_SERVER}" dir="/" timeout="360"/>
   </interface>
   
   <command name="set_app_rel_src">
      <execute>
         print $1
      </execute>
      <resultsblock>
         <match pattern="^([a-zA-Z]+)_(\d\d\.\d\.\d\.\d)_([A-Za-z]{3})$">
            <setenv name="APPLICATION"          value="$1"/>
            <setenv name="RELEASE"              value="$2"/>
            <setenv name="SOURCE_STREAM"   value="$3" />
         </match>
      </resultsblock>      
   </command>
   
   <command name="set_prev_source_stream">
      <execute>
         if [ $1 eq "SIT" ]; then
               print "DEV"
            elsif [ $1 eq "UAT" ]; then
               print "SIT"
            else; then
               print "DEV"
         fi
      </execute>
      <resultsblock>
         <match pattern="^([A-Za-z]{3})$">
            <setenv name="PREV_SOURCE_STREAM"   value="$1" />
         </match>
      </resultsblock>
   </command>
   
   <command name="print_it">
      <execute>
         print "print_it = " . $1
      </execute>
   </command>
   
   <command name="clean_system_outs">
      <execute>
         /usr/bin/perl system_out_clean.pl --stream=$2 --action=$3
      </execute>
      <resultsblock>
         <match pattern="^">
            <bom category="System.out.printlns" section="File Name">
               <field name="file" text="$_"/>
            </bom>
         </match>
      </resultsblock>
   </command>   
   
   <bomformat category="System.out.printlns" title="System.out.printlns">
      <section name="File Name" expandable="true">
         <field order="1" name="file" title="Files"/>         
      </section>
   </bomformat>
</PROJECT_INTERFACE>
