=== greenscar/scripts/buildforge/interface.dtd
<!ELEMENT PROJECT_INTERFACE (template*,interface,command+,bomformat+)>
<!ATTLIST PROJECT_INTERFACE IFTYPE CDATA #REQUIRED>
<!ATTLIST PROJECT_INTERFACE INSTANCE CDATA #REQUIRED>
<!ELEMENT template (env+)>
<!ELEMENT interface (setenv*,adduser*,relate*,run+,adduser*,relate*,ontempenv*,onstep*,onproject*,setenv*,adduser*,relate*,ontempenv*,onstep*,onproject*)>
<!ATTLIST interface name CDATA #IMPLIED>
<!ELEMENT command (execute*,integrate*,resultsblock+)>
<!ATTLIST command name CDATA #REQUIRED>
<!ATTLIST command type (exec | conjoined | parallel) #IMPLIED>
<!ELEMENT bomformat (section+)>
<!ATTLIST bomformat category CDATA #REQUIRED>
<!ATTLIST bomformat title CDATA #REQUIRED>
<!ELEMENT env EMPTY>
<!ATTLIST env name CDATA #REQUIRED>
<!ATTLIST env value CDATA #REQUIRED>
<!ELEMENT setenv EMPTY>
<!ATTLIST setenv group CDATA #IMPLIED>
<!ATTLIST setenv name CDATA #REQUIRED>
<!ATTLIST setenv value CDATA #REQUIRED>
<!ATTLIST setenv type CDATA #IMPLIED>
<!ATTLIST setenv eval CDATA #IMPLIED>
<!ATTLIST setenv condition CDATA #IMPLIED>
<!ELEMENT run EMPTY>
<!ATTLIST run command CDATA #REQUIRED>
<!ATTLIST run params CDATA #REQUIRED>
<!ATTLIST run server CDATA #REQUIRED>
<!ATTLIST run dir CDATA #REQUIRED>
<!ATTLIST run timeout CDATA #IMPLIED>
<!ATTLIST run condition CDATA #IMPLIED>
<!ATTLIST run mode (exec | conjoined | parallel) #IMPLIED>
<!ELEMENT ontempenv (step+,setenv*)>
<!ATTLIST ontempenv name CDATA #REQUIRED>
<!ATTLIST ontempenv state (empty | hastext | true | false) #REQUIRED>
<!ELEMENT onproject (notify+)>
<!ATTLIST onproject result (PASS|FAIL|pass|fail) #REQUIRED>
<!ELEMENT onstep (setenv*)>
<!ATTLIST onstep result (PASS|FAIL|pass|fail) #REQUIRED>
<!ELEMENT execute (#PCDATA)>
<!ELEMENT integrate (#PCDATA)>
<!ELEMENT resultsblock (match*,setenv*,resultsblock*,match*,setenv*,resultsblock*)>
<!ATTLIST resultsblock beginpattern CDATA #IMPLIED>
<!ATTLIST resultsblock endpattern CDATA #IMPLIED>
<!ELEMENT section (field+)>
<!ATTLIST section name CDATA #REQUIRED>
<!ATTLIST section parent CDATA #IMPLIED>
<!ATTLIST section expandable (true|false) #IMPLIED>
<!ELEMENT step EMPTY>
<!ATTLIST step result (FAIL|PASS|fail|pass) #REQUIRED>
<!ELEMENT notify EMPTY>
<!ATTLIST notify group CDATA #REQUIRED>
<!ATTLIST notify subject CDATA #REQUIRED>
<!ATTLIST notify message CDATA #REQUIRED>
<!ELEMENT match (bom*,adduser*,relate*,setenv*,run*,bom*,adduser*,relate*,setenv*,run*)>
<!ATTLIST match pattern CDATA #REQUIRED>
<!ELEMENT field EMPTY>
<!ATTLIST field name CDATA #REQUIRED>
<!ATTLIST field text CDATA #IMPLIED>
<!ATTLIST field order CDATA #IMPLIED>
<!ATTLIST field title CDATA #IMPLIED>
<!ELEMENT bom (field+)>
<!ATTLIST bom category CDATA #REQUIRED>
<!ATTLIST bom section CDATA #REQUIRED>
<!ATTLIST bom condition CDATA #IMPLIED>
<!ELEMENT adduser EMPTY>
<!ATTLIST adduser group CDATA #REQUIRED>
<!ATTLIST adduser user CDATA #REQUIRED>
<!ATTLIST adduser condition CDATA #IMPLIED>
<!ELEMENT relate EMPTY>
<!ATTLIST relate artifact CDATA #REQUIRED>
<!ATTLIST relate user CDATA #REQUIRED>

=== greenscar/scripts/buildforge/get_bls.xml
<!DOCTYPE PROJECT_INTERFACE SYSTEM "interface.dtd">
<PROJECT_INTERFACE IFTYPE="Source" INSTANCE="7.02">
   <template>
      <env name="VIEW_NAME"     value="required"/>
      <env name="BF_SERVER"         value="required"/>
      <env name="BF_ROOT"           value="required"/>
		<env name="CUR_DATE"          value="required" />
   </template>
   
   <interface>      
      <run command="figure_app" params="$VIEW_NAME" server="$BF_SERVER" dir="/" timeout="120"/>
	   <run command="get_bls_ssp" params="$VIEW_NAME" server="$BF_SERVER" dir="/" timeout="120" condition="true('$app' eq 'SSP')"/>
      <run command="get_bls_stp" params="$VIEW_NAME" server="$BF_SERVER" dir="/" timeout="120" condition="true('$app' eq 'STP')"/>
      <run command="get_bls_tlm" params="$VIEW_NAME" server="$BF_SERVER" dir="/" timeout="120" condition="true('$app' eq 'TLM')"/>
      <run command="get_bls_snbx" params="$VIEW_NAME" server="$BF_SERVER" dir="/" timeout="120" condition="true('$app' eq 'SNBX')"/>
      <run command="get_bls_tiers" params="$VIEW_NAME" server="$BF_SERVER" dir="/" timeout="120" condition="true('$app' eq 'TIERS')"/>
   </interface>
   
   <command name="figure_app">
      <execute>
         echo '$1'
      </execute>
      <resultsblock>
         <match pattern="(SSP)">
            <setenv name="app" value="SSP" type="temp"/>
         </match>
         <match pattern="(STP)">
            <setenv name="app" value="STP" type="temp"/>
         </match>
         <match pattern="(TLM)">
            <setenv name="app" value="TLM" type="temp"/>
         </match>
         <match pattern="(TIERS)">
            <setenv name="app" value="TLM" type="temp"/>
         </match>
         <match pattern="(SNBX)">
            <setenv name="app" value="SNBX" type="temp"/>
         </match>
      </resultsblock>
   </command>
   
   
   <command name="get_bls_ssp">
      <execute>
         ${BF_ROOT}get_bls.pl --srcstream "$1"
      </execute>
      <resultsblock>
         <match pattern="^bl_dev=(.+)$">
            <bom category="blssp" section="sspbaselines">
               <field name="DEV" text="$1"/>
            </bom>
         </match>
         <match pattern="^bl_sit=(.+)$">
            <bom category="blssp" section="sspbaselines">
               <field name="SIT" text="$1"/>
            </bom>
         </match>
         <match pattern="^bl_uat=(.+)$">
            <bom category="blssp" section="sspbaselines">
               <field name="UAT" text="$1"/>
            </bom>
         </match>
      </resultsblock>
   </command>
   
   <command name="get_bls_stp">
      <execute>
         ${BF_ROOT}get_bls.pl --srcstream "$1"
      </execute>
      <resultsblock>
         <match pattern="^bl_dev=(.+)$">
            <bom category="blstp" section="stpbaselines">
               <field name="DEV" text="$1"/>
            </bom>
         </match>
         <match pattern="^bl_sit=(.+)$">
            <bom category="blstp" section="stpbaselines">
               <field name="SIT" text="$1"/>
            </bom>
         </match>
         <match pattern="^bl_uat=(.+)$">
            <bom category="blstp" section="stpbaselines">
               <field name="UAT" text="$1"/>
            </bom>
         </match>
      </resultsblock>
   </command>
   
   
   <command name="get_bls_tlm">
      <execute>
         ${BF_ROOT}get_bls.pl --srcstream "$1"
      </execute>
      <resultsblock>
         <match pattern="^bl_dev=(.+)$">
            <bom category="bltlm" section="tlmbaselines">
               <field name="DEV" text="$1"/>
            </bom>
         </match>
         <match pattern="^bl_sit=(.+)$">
            <bom category="bltlm" section="tlmbaselines">
               <field name="SIT" text="$1"/>
            </bom>
         </match>
         <match pattern="^bl_uat=(.+)$">
            <bom category="bltlm" section="tlmbaselines">
               <field name="UAT" text="$1"/>
            </bom>
         </match>
      </resultsblock>
   </command>
   
   <command name="get_bls_tiers">
      <execute>
         ${BF_ROOT}get_bls.pl --srcstream "$1"
      </execute>
      <resultsblock>
         <match pattern="^bl_dev=(.+)$">
            <bom category="bltiers" section="tiersbaselines">
               <field name="DEV" text="$1"/>
            </bom>
         </match>
         <match pattern="^bl_sit=(.+)$">
            <bom category="bltiers" section="tiersbaselines">
               <field name="SIT" text="$1"/>
            </bom>
         </match>
         <match pattern="^bl_uat=(.+)$">
            <bom category="bltiers" section="tiersbaselines">
               <field name="UAT" text="$1"/>
            </bom>
         </match>
      </resultsblock>
   </command>
   
   <command name="get_bls_snbx">
      <execute>
         ${BF_ROOT}get_bls.pl --srcstream "$1"
      </execute>
      <resultsblock>
         <match pattern="^bl_dev=(.+)$">
            <bom category="blsnbx" section="snbxbaselines">
               <field name="DEV" text="$1"/>
            </bom>
         </match>
         <match pattern="^bl_sit=(.+)$">
            <bom category="blsnbx" section="snbxbaselines">
               <field name="SIT" text="$1"/>
            </bom>
         </match>
         <match pattern="^bl_uat=(.+)$">
            <bom category="blsnbx" section="snbxbaselines">
               <field name="UAT" text="$1"/>
            </bom>
         </match>
      </resultsblock>
   </command>
   
   <bomformat category="blssp" title="SSP Baseline Report">
      <section name="sspbaselines">
         <field order="1" name="DEV" title="DEV"/>
         <field order="2" name="SIT" title="SIT"/>
         <field order="3" name="UAT" title="UAT"/>
      </section>
   </bomformat>
   
		
    
   <bomformat category="blstp" title="STP Baseline Report">
      <section name="stpbaselines">
         <field order="1" name="DEV" title="DEV"/>
         <field order="2" name="SIT" title="SIT"/>
         <field order="3" name="UAT" title="UAT"/>
      </section>
   </bomformat>
   
    
   <bomformat category="bltlm" title="TLM Baseline Report">
      <section name="tlmbaselines">
         <field order="1" name="DEV" title="DEV"/>
         <field order="2" name="SIT" title="SIT"/>
         <field order="3" name="UAT" title="UAT"/>
      </section>
   </bomformat>
   
   
   <bomformat category="bltiers" title="TIERS Baseline Report">
      <section name="tiersbaselines">
         <field order="1" name="DEV" title="DEV"/>
         <field order="2" name="SIT" title="SIT"/>
         <field order="3" name="UAT" title="UAT"/>
      </section>
   </bomformat>
   
   
   
   <bomformat category="blsnbx" title="SNBX Baseline Report">
      <section name="snbxbaselines">
         <field order="1" name="DEV" title="DEV"/>
         <field order="2" name="SIT" title="SIT"/>
         <field order="3" name="UAT" title="UAT"/>
      </section>
   </bomformat>
   
</PROJECT_INTERFACE>

=== greenscar/scripts/buildforge/bldiffreport_75.xml
<!DOCTYPE PROJECT_INTERFACE SYSTEM "interface.dtd">
<PROJECT_INTERFACE IFTYPE="Source" INSTANCE="7.02">
   <template>
		<!-- Template section, these are parsed out of the final xml and used to populate an 
		existing environment group if an instance of this interface is linked with a project.
		However, use the list below to help identify the variables needed to run this interface
		if you are integrating it during a regular BuildForge step.
		-->
		<env name="CurDate"              value=".date %d-%b-%y.%H:%M:%S" />
      <env name="APP"     value="required"/>
      <env name="RELEASE_NUM" value="required"/>
      <env name="SOURCE_STREAM" value="required"/>
		<env name="PVOB"                 value="snbx_project" />
		<env name="BF_SERVER"            value="BFServerName" />
      <env name="BF_ROOT"              value="required"/>
      <env name="BF_USER_EMAIL"        value="required"/>
      <env name="testlvl"              value="Defined by autobl"/>
	</template>
   
	<!-- The 'ByBaseline' entry point will create a new baseline inside your source, and will then diff between the 
	newly crated baseline, and the baseline created during the previous build of the project -->
	<interface>
		<!-- The internal variable 'Changing' is used to store an email template that we will dynamically generate -->
		<setenv name="Changing" value="Source Changes for this Build:\n" type="temp"/>
		<setenv name="NoChanges" value="There are no Source Changes for this Build.\n" type="temp"/>
      <setenv name="VIEW_NAME" value="${APP}_${RELEASE_NUM}_${SOURCE_STREAM}" type="temp" condition="isempty('VIEW_NAME')"/>
		
		<adduser group="MyChangers" user="$BF_USER_EMAIL"/>
		<!-- cc_baselineactivities is detailed below but is basically the entry point into the command set to gather change info" -->
      <run command="cc_baselineactivities" params="$OLDBL $NEWBL $SOURCE_STREAM $PVOB" server="$BF_SERVER" dir="/" timeout="360" condition="false($testlvl eq $LOCAL)"/>
		<!-- Here we test to see if we have any changes, 'Changes' should have some data if a change was found -->
		<ontempenv name="Changes" state="empty">
			<!-- No changes, fail the build, default behaviour is pass -->
			<step result="FAIL"/>
		</ontempenv>
		
      <!-- Set some notifications for when the build completes -->
		<onproject result="fail">
			<notify group="MyChangers" subject="Build $BF_TAG (${CurDate}) Canceled due to no code changes." message="${NoChanges}"/>
		</onproject>
		<onproject result="pass">
			<notify group="MyChangers" subject="Build $BF_TAG (${CurDate}) Passed." message="${Changing}${Changes}"/>
		</onproject>
	</interface>
   <!-- 
      This command lists the activities that occurred between two baselines, 
		it then calls cc_actdescribe to gather further details about the activities -->
	<command name="cc_baselineactivities">
		<execute>
         cd $3
         cleartool diffbl -act $1@\$4 $2@\$4
		</execute>
		<resultsblock>
			<match pattern="^[->]>\s+([^\s].*?)\s.*$">
				<run command="cc_actdescribe" params="$SOURCE_STREAM $1" server="$BF_SERVER" dir="/" timeout="360"/>
			</match>
		</resultsblock>
	</command>
	<!-- This command gathers details about an activity and logs pertinent information to the BuildForge BOM -->
	<command name="cc_actdescribe">
		<execute>
         cd $1
         cleartool lsact -l $2
		</execute>
		<resultsblock>
			<!-- look for something resempling an activity identifier -->
			<match pattern="^activity\s&quot;(.*?)&quot;$">
				<bom category="Source" section="activities">
					<field name="id" text="$1"/>
				</bom>
			</match>
			<!-- look for an activity owner -->
			<match pattern="owner:\s(.*?\\|)(.*?)$">
				<bom category="Source" section="activities">
					<field name="owner" text="${1}${2}"/>
				</bom>
				<!-- add the user to our list of people who contributed changes to this build -->
				<adduser group="MyChangers" user="$2"/>
			</match>
			<!-- look for some stream information -->
			<match pattern="stream:\s(.*?)$">
				<bom category="Source" section="activities">
					<field name="stream" text="$1"/>
				</bom>
			</match>
			<!-- See if we get a title for this activity -->
			<match pattern="title:\s(.*?)$">
				<bom category="Source" section="activities">
					<field name="title" text="$1"/>
				</bom>
			</match>
			<!-- This identifies any file/directory changes within the activity -->
			<match pattern="^\s+([\\/].*?)\@\@(.*?\d)$">
				<bom category="Source" section="changeset">
					<field name="version" text="$1@@$2"/>
				</bom>
				<!-- add the information to our email template -->
				<setenv name="Changes" value="$1\@\@$2" type="temp append\n"/>
				<!-- and then run cc_diff to log the differences associated with this changed object -->
				<run command="cc_diff" params="$SOURCE_STREAM $1 $2" server="$BF_SERVER" dir="/" timeout="360"/>
			</match>
			<!-- Log clearquest info if we get a record -->
			<match pattern="clearquest record id:\s(.*?)$">
				<bom category="Source" section="clearquestinfo">
					<field name="cqid" text="$1"/>
				</bom>
			</match>
			<match pattern="clearquest record State:\s(.*?)$">
				<bom category="Source" section="clearquestinfo">
					<field name="cqstate" text="$1"/>
				</bom>
			</match>
		</resultsblock>
	</command>
	<!-- The cc_diff command does a generic clearcase diff, logging the full output of the diff in the BuildForge BOM -->
	<command name="cc_diff">
		<execute>
         cd $1 
         cleartool diff -pred -diff_format &quot;$2@@$3&quot;
		</execute>
		<resultsblock>
			<match pattern=".+">
				<bom category="Source" section="diff">
					<field name="diff" text="$_"/>
				</bom>
			</match>
		</resultsblock>
	</command>
	<!-- The bomformat sets up the BuildForge BOM display for the information we gather during this interface execution -->
	<!-- A category is a top level expandable item -->
	<bomformat category="Source" title="Source Changes">
		<!-- A section defines the columns for blocks of information, a new row of information is added 
			each time the last field (by order number) in a block is populated with new information -->
		<section name="changes">
			<field order="1" name="file" title="File/Dir Name"/>
			<field order="2" name="version" title="Version"/>
			<field order="3" name="date" title="Date"/>
			<field order="4" name="user" title="User"/>
			<field order="5" name="comment" title="Comment"/>
		</section>
		<section name="activities">
			<field order="1" name="id" title="Activity"/>
			<field order="2" name="owner" title="Owner"/>
			<field order="3" name="stream" title="Stream"/>
			<field order="4" name="title" title="Title"/>
		</section>
		<section name="changeset">
			<field order="1" name="version" title="Change set version"/>
		</section>
		<section name="clearquestinfo">
			<field order="1" name="cqid" title="ClearQuest record ID"/>
			<field order="2" name="cqstate" title="ClearQuest record state"/>
		</section>
		<section name="diff">
			<field name="diff" title="Change Details"/>
		</section>
	</bomformat>
</PROJECT_INTERFACE>

=== greenscar/scripts/buildforge/system.out.println.report.75.xml
<!DOCTYPE PROJECT_INTERFACE SYSTEM "interface.dtd">
<PROJECT_INTERFACE IFTYPE="Source" INSTANCE="7.02">
   <template>
      <!-- Template section, these are parsed out of the final xml and used to populate an 
      existing environment group if an instance of this interface is linked with a project.
      However, use the list below to help identify the variables needed to run this interface
      if you are integrating it during a regular BuildForge step.
      -->
   
      <env name="APP"     value="required"/>
      <env name="RELEASE_NUM" value="required"/>
      <env name="SOURCE_STREAM" value="required"/>
      <env name="BF_SERVER"   value="iedaau020_wasadmin"/>
      <env name="SYSCONFIG_VIEW"    value="required"/>
      <env name="BF_SERVER_ROOT" value="required"/>
   </template>
   
   <interface>  
      <setenv name="VIEW_NAME" value="${APP}_${RELEASE_NUM}_${SOURCE_STREAM}" type="temp"/>
	   <run command="cleanssp" params="$VIEW_NAME" server="$BF_SERVER" timeout="600" condition="true('$APP' eq 'SSP')"/>
      <run command="cleanstp" params="$VIEW_NAME" server="$BF_SERVER" timeout="600" condition="true('$APP' eq 'STP')"/>
      <run command="cleantlm" params="$VIEW_NAME" server="$BF_SERVER" timeout="600" condition="true('$APP' eq 'TLM')"/>
   </interface>
   
   <command name="echo">
      <execute>
         echo '$1'
      </execute>
      <resultsblock>
         <match pattern="(.*)">
            <setenv name="x" value="${1}" type="temp"/>
         </match>
      </resultsblock>
   </command>
   
   <command name="figure_app">
      <execute>
         echo '$1'
      </execute>
      <resultsblock>
         <match pattern="(SSP)">
            <setenv name="app" value="SSP" type="temp"/>
         </match>
         <match pattern="(STP)">
            <setenv name="app" value="STP" type="temp"/>
         </match>
         <match pattern="(TLM)">
            <setenv name="app" value="TLM" type="temp"/>
         </match>
      </resultsblock>
   </command>
   
   <command name="cleantlm">
      <execute>
         ${loadprofile}
         /usr/bin/perl ${BF_ROOT}/${SYSCONFIG_VIEW}/pbad/scripts/perl/system_out_clean.pl --stream=$1 --action=replace
      </execute>
      <resultsblock>
         <match pattern="((^\s)*)">
            <bom category="tlmsop" section="tlmfiles">
               <field name="tlmfile" text="$_"/>
            </bom>
         </match>
      </resultsblock>
   </command>

   <command name="cleanstp">
      <execute>
         ${loadprofile}
         /usr/bin/perl ${BF_ROOT}/${SYSCONFIG_VIEW}/pbad/scripts/perl/system_out_clean.pl --stream=$1 --action=replace
      </execute>
      <resultsblock>
         <match pattern="((^\s)*)">
            <bom category="stpsop" section="stpfiles">
               <field name="stpfile" text="$_"/>
            </bom>
         </match>
      </resultsblock>
   </command>      
   
   <command name="cleanssp">
      <execute>
         ${loadprofile}
         /usr/bin/perl ${BF_ROOT}/${SYSCONFIG_VIEW}/pbad/scripts/perl/system_out_clean.pl --stream=$1 --action=replace
      </execute>
      <resultsblock>
         <match pattern="((^\s)*)">
            <bom category="sspsop" section="sspfiles">
               <field name="sspfile" text="$_"/>
            </bom>
         </match>
      </resultsblock>
   </command>      
   
   <bomformat category="sspsop" title="STP System.out.printlns">
      <section name="sspfiles">
         <field order="1" name="sspfile" title="Files"/>         
      </section>
   </bomformat>
   
   <bomformat category="stpsop" title="STP System.out.printlns">
      <section name="stpfiles">
         <field order="1" name="stpfile" title="Files"/>         
      </section>
   </bomformat>
   
   <bomformat category="tlmsop" title="TLM System.out.printlns">
      <section name="tlmfiles">
         <field order="1" name="tlmfile" title="Files"/>         
      </section>
   </bomformat>
   
   
</PROJECT_INTERFACE>

=== greenscar/scripts/buildforge/ClearQuestUCMClearCaseByDate.xml
<?xml version="1.0"?>
<!-- (c) Copyright by IBM Corp. and other(s) [2003], 2007 All Rights Reserved. -->
<!DOCTYPE PROJECT_INTERFACE SYSTEM "interface.dtd">
<PROJECT_INTERFACE IFTYPE="Defect" INSTANCE="7.021">
	<template>
		<!-- Template section, these are parsed out of the final xml and used to populate an 
		existing environment group if an instance of this interface is linked with a project.
		However, use the list below to help identify the variables needed to run this interface
		if you are integrating it during a regular BuildForge step.
		-->
		<env name="CurDate" value=".date %d-%b-%y.%H:%M:%S"/>
		<env name="LAST_RUN" value="1-Jan-05.00:00:00"/>
		<env name="VIEW" value="my_interface_view"/>
		<env name="VOB_PATH" value="\AdaptorVob"/>
		<env name="CQ_USER" value="admin"/>
		<env name="CQ_PASSWORD" value=""/>
		<env name="BFSERVER" value="BFServerName"/>
		<env name="UNIXCLIENT" value="0"/>
		<env name="_CHAR_NATIVE" value="1" />
	</template>
	<!-- The ClearCaseByDate entry point is used to identify clearquest records that have been associated with 
	clearcase changes since the last run of this particular instance of the interface -->
	<interface>
		<!-- In this interface, 'Resolving' and 'Erroring' are two templates that will be used to construct an email post-build -->
		<setenv name="Resolving" value="- ClearQuest Defect Records associated with this build -\n" type="temp"/>
		<setenv name="Erroring" value="\n- The following errors occurred while interacting with ClearQuest -\n" type="temp"/>

		<!-- Set some platform specific information -->
		<setenv name="CdCommand" value="cd /view" type="temp" condition="true($UNIXCLIENT==1)"/>
		<setenv name="CdCommand" value="pushd \\view" type="temp" condition="true($UNIXCLIENT==0)"/>
		<setenv name="DirSep" value="/" type="temp" condition="true($UNIXCLIENT==1)"/>
		<setenv name="DirSep" value="\" type="temp" condition="true($UNIXCLIENT==0)"/>
		
		<!-- MyChanges is the start of the list of users to be emailed with change information -->
		<adduser group="MyChangers" user="cmadmins@mycompany.com"/>
		<!-- cc_cq_changes is the initial command that will query clearcase for 
			clearquest defect information, and modify the defect -->
		<run command="cc_cq_changes" params="$LAST_RUN $VIEW $VOB_PATH" server="$BFSERVER" dir="/" timeout="360"/>
		<!-- Here we test to see if we have any errors, 'Errors' should have some data if an error was found -->
		<ontempenv name="Errors" state="hastext">
			<step result="FAIL"/>
		</ontempenv>
		<ontempenv name="Resolved" state="empty">
			<step result="FAIL"/>
		</ontempenv>
		<!-- If there were no errors, then update our environment for the next run -->
		<onstep result="pass">
			<setenv group="[ADAPTOR]" name="LAST_RUN" value="$CurDate"/>
		</onstep>
		<!-- Set some notifications for when the build completes -->
		<onproject result="fail">
			<notify group="MyChangers" subject="Build $BF_TAG ($CurDate) Failed." message="${Resolving}${Resolved}${Erroring}${Errors}"/>
		</onproject>
		<onproject result="pass">
			<notify group="MyChangers" subject="Build $BF_TAG ($CurDate) Passed." message="${Resolving}${Resolved}"/>
		</onproject>
	</interface>
	<!-- Searches the view location for any base cc/cq integrated records (CrmRequest type hyperlinks) -->
	<command name="cc_cq_changes">
		<execute>
cleartool startview $2
$CdCommand${DirSep}$2 &amp;&amp; cleartool find .$3 -all -cview -version "created_since($1)" -print
		</execute>
		<resultsblock>
			<match pattern="^(.*?)(\@\@.*?\d+)$">
				<run command="cq_getcrm" params="$VIEW ${1}${2}" server="$BFSERVER" dir="/" timeout="360"/>
			</match>
		</resultsblock>
	</command>
	<!-- Gathers more information on the ClearQuest hyperlink -->
	<command name="cq_getcrm">
		<execute>
$CdCommand${DirSep}$1 &amp;&amp; cleartool describe -long $2
		</execute>
		<resultsblock>
			<match pattern="\W(.*?)(\@\@.*?\d+)\W">
				<bom category="ClearCase" section="changes">
					<field name="vobj" text="${1}${2}"/>
				</bom>
			</match>
			<match pattern="\d+-\d+-.+\s.+\s(.*?)$">
				<bom category="ClearCase" section="changes">
					<field name="user" text="$1"/>
				</bom>
			</match>
			<match pattern="^\s+activity:(.*?)\@(.*?)\s+(.*?)$">
				<bom category="ClearCase" section="changes">
					<field name="activity" text="${1}"/>
					<field name="headline" text="${3}"/>
				</bom>
				<setenv name="CurAct" value="$1" type="temp"/>
				<setenv name="$CurAct" value="" type="temp once"/>
				<run command="cq_resolve" params="$1" server="" dir="/" condition="false($$1==1)"/>
			</match>
		</resultsblock>
	</command>
	<!-- Executes the integration script 'cq_resolve' to resolve defects in ClearQuest -->
	<command name="cq_resolve">
		<integrate>
cqperl bfcqresolve.pl $1 Fixed "Fixed in build $BF_TAG"
		</integrate>
		<resultsblock>
			<resultsblock beginpattern="^ERROR:">
				<match pattern="^(.*?)$">
					<bom category="CQErrors" section="text">
						<field name="Error" text="$1"/>
					</bom>
					<setenv name="Errors" value="$1\n" type="temp append\n"/>
				</match>
			</resultsblock>
			<resultsblock beginpattern="^(?!ERROR:).+">
				<match pattern="^(.+)$">
					<bom category="defects" section="resolve_status">
						<field name="defectid" text="$CurAct"/>
						<field name="status" text="$1"/>
					</bom>
					<setenv name="Resolved" value="$1\n" type="temp append\n"/>
					<setenv name="$CurAct" value="1" type="temp"/>
				</match>
			</resultsblock>
		</resultsblock>
	</command>
	<!-- The bomformat sets up the BuildForge BOM display for the information we gather during this interface execution -->
	<!-- A category is a top level expandable item -->
	<bomformat category="ClearCase" title="ClearCase Change Information">
		<!-- A section defines the columns for blocks of information, a new row of information is added 
			each time the last field (by order number) in a block is populated with new information -->
		<section name="changes">
			<field order="1" name="vobj" title="Vob Object"/>
			<field order="2" name="user" title="User Id"/>
			<field order="3" name="activity" title="Activity/Defect Id"/>
			<field order="4" name="headline" title="Headline"/>
		</section>
	</bomformat>
	<bomformat category="defects" title="ClearQuest Defect Information">
		<section name="resolve_status">
			<field order="1" name="defectid" title="DefectId"/>
			<field order="2" name="status" title="Status"/>
		</section>
	</bomformat>
	<bomformat category="CQErrors" title="ClearQuest Interaction Errors">
		<section name="text">
			<field order="1" name="Error" title="Error Details"/>
		</section>
	</bomformat>
</PROJECT_INTERFACE>

=== greenscar/scripts/buildforge/system.out.println.report.xml
<!DOCTYPE PROJECT_INTERFACE SYSTEM "interface.dtd">
<PROJECT_INTERFACE IFTYPE="Source" INSTANCE="7.02">
   <template>
      <!-- Template section, these are parsed out of the final xml and used to populate an 
      existing environment group if an instance of this interface is linked with a project.
      However, use the list below to help identify the variables needed to run this interface
      if you are integrating it during a regular BuildForge step.
      -->
      <env name="VIEW_NAME"        value="view"/>
      <env name="BF_SERVER"   value="iedaau020_wasadmin"/>
      <env name="PBAD_DIR"    value="pbad_dir"/>
   </template>
   
   <interface>
   
      <run command="clean_system_outs" params="$VIEW_NAME" server="$BF_SERVER" dir="${PBAD_DIR}/scripts/perl" timeout="600"/>
   </interface>
   
   <command name="clean_system_outs">
      <execute>
         /usr/bin/perl system_out_clean.pl --stream=$1 --action=replace
      </execute>
      <resultsblock>
         <match pattern="((^\s)*)">
            <bom category="System.out.printlns" section="Files">
               <field name="file" text="$_"/>
            </bom>
         </match>
      </resultsblock>
   </command>   
   
   <bomformat category="System.out.printlns" title="System.out.printlns">
      <section name="Files" expandable="true">
         <field order="1" name="file" title="Files"/>         
      </section>
   </bomformat>
</PROJECT_INTERFACE>
