=== greenscar/scripts/buildforge/interface.dtd
<!ELEMENT PROJECT_INTERFACE (template*,interface,command+,bomformat+)>
<!ATTLIST PROJECT_INTERFACE IFTYPE CDATA #REQUIRED>
<!ATTLIST PROJECT_INTERFACE INSTANCE CDATA #REQUIRED>
<!ELEMENT template (env+)>
<!ELEMENT interface (setenv*,adduser*,relate*,run+,adduser*,relate*,ontempenv*,onstep*,onproject*,setenv*,adduser*,relate*,ontempenv*,onstep*,onproject*)>
<!ATTLIST interface name CDATA #IMPLIED>
<!ELEMENT command (execute*,integrate*,resultsblock+)>
<!ATTLIST command name CDATA #REQUIRED>
<!ATTLIST command type (exec | conjoined | parallel) #IMPLIED>
<!ELEMENT bomformat (section+)>
<!ATTLIST bomformat category CDATA #REQUIRED>
<!ATTLIST bomformat title CDATA #REQUIRED>
<!ELEMENT env EMPTY>
<!ATTLIST env name CDATA #REQUIRED>
<!ATTLIST env value CDATA #REQUIRED>
<!ELEMENT setenv EMPTY>
<!ATTLIST setenv group CDATA #IMPLIED>
<!ATTLIST setenv name CDATA #REQUIRED>
<!ATTLIST setenv value CDATA #REQUIRED>
<!ATTLIST setenv type CDATA #IMPLIED>
<!ATTLIST setenv eval CDATA #IMPLIED>
<!ATTLIST setenv condition CDATA #IMPLIED>
<!ELEMENT run EMPTY>
<!ATTLIST run command CDATA #REQUIRED>
<!ATTLIST run params CDATA #REQUIRED>
<!ATTLIST run server CDATA #REQUIRED>
<!ATTLIST run dir CDATA #REQUIRED>
<!ATTLIST run timeout CDATA #IMPLIED>
<!ATTLIST run condition CDATA #IMPLIED>
<!ATTLIST run mode (exec | conjoined | parallel) #IMPLIED>
<!ELEMENT ontempenv (step+,setenv*)>
<!ATTLIST ontempenv name CDATA #REQUIRED>
<!ATTLIST ontempenv state (empty | hastext | true | false) #REQUIRED>
<!ELEMENT onproject (notify+)>
<!ATTLIST onproject result (PASS|FAIL|pass|fail) #REQUIRED>
<!ELEMENT onstep (setenv*)>
<!ATTLIST onstep result (PASS|FAIL|pass|fail) #REQUIRED>
<!ELEMENT execute (#PCDATA)>
<!ELEMENT integrate (#PCDATA)>
<!ELEMENT resultsblock (match*,setenv*,resultsblock*,match*,setenv*,resultsblock*)>
<!ATTLIST resultsblock beginpattern CDATA #IMPLIED>
<!ATTLIST resultsblock endpattern CDATA #IMPLIED>
<!ELEMENT section (field+)>
<!ATTLIST section name CDATA #REQUIRED>
<!ATTLIST section parent CDATA #IMPLIED>
<!ATTLIST section expandable (true|false) #IMPLIED>
<!ELEMENT step EMPTY>
<!ATTLIST step result (FAIL|PASS|fail|pass) #REQUIRED>
<!ELEMENT notify EMPTY>
<!ATTLIST notify group CDATA #REQUIRED>
<!ATTLIST notify subject CDATA #REQUIRED>
<!ATTLIST notify message CDATA #REQUIRED>
<!ELEMENT match (bom*,adduser*,relate*,setenv*,run*,bom*,adduser*,relate*,setenv*,run*)>
<!ATTLIST match pattern CDATA #REQUIRED>
<!ELEMENT field EMPTY>
<!ATTLIST field name CDATA #REQUIRED>
<!ATTLIST field text CDATA #IMPLIED>
<!ATTLIST field order CDATA #IMPLIED>
<!ATTLIST field title CDATA #IMPLIED>
<!ELEMENT bom (field+)>
<!ATTLIST bom category CDATA #REQUIRED>
<!ATTLIST bom section CDATA #REQUIRED>
<!ATTLIST bom condition CDATA #IMPLIED>
<!ELEMENT adduser EMPTY>
<!ATTLIST adduser group CDATA #REQUIRED>
<!ATTLIST adduser user CDATA #REQUIRED>
<!ATTLIST adduser condition CDATA #IMPLIED>
<!ELEMENT relate EMPTY>
<!ATTLIST relate artifact CDATA #REQUIRED>
<!ATTLIST relate user CDATA #REQUIRED>

=== greenscar/scripts/buildforge/autobl_and_bl_diff_report_rev2.xml
<!DOCTYPE PROJECT_INTERFACE SYSTEM "interface.dtd">
<PROJECT_INTERFACE IFTYPE="Source" INSTANCE="7.02">
   <template>
      <env name="VIEW_NAME"     value="required"/>
      <env name="PVOB"              value="required"/>
      <env name="BF_SERVER"         value="required"/>
      <env name="BF_ROOT"           value="required"/>
      <env name="BF_USER_EMAIL"     value="required"/>
		<env name="CUR_DATE"          value="required" />
      <env name="DO_REBASE"         value="YES"/>
   </template>
   
   <interface>      
		<adduser group="MyChangers" user="$BF_USER_EMAIL"/>
      <setenv name="NEWBL" value="" type="temp"/>
      
      <run command="check_test_lvl" params="$VIEW_NAME" server="$BF_SERVER" dir="/" timeout="120" condition="true('$DO_REBASE' eq 'YES')"/>
      <run command="set_bl_vars" params="$VIEW_NAME $STREAM_LEVEL" server="$BF_SERVER" dir="/" timeout="120" condition="true('$DO_REBASE' eq 'YES')"/>
      
      <run command="autobl" params="$B $VIEW_NAME $BF_ROOT $BL_DEV $BL_SIT $BL_UAT" server="$BF_SERVER" dir="/" timeout="600" condition="true('$DO_REBASE' eq 'YES')"/>
      <run command="cc_baselineactivities" params="$OLDBL $NEWBL $VIEW_NAME $PVOB" server="$BF_SERVER" dir="/" timeout="360" condition="hastext($NEWBL)"/>
      
   </interface>
   
   <command name="set_bl_vars">
      <execute>
         #!/usr/bin/perl
         echo(
      </execute>
   </command>
   <command name="check_test_lvl">
      <execute>
         echo '$1'
      </execute>
      <resultsblock>
         <match pattern="(LOCAL)">
            <setenv name="DO_REBASE" value="NO" type="temp"/>
            <setenv name="STREAM_LEVEL" value="${1}" type="temp"/>
         </match>
         <match pattern="(DEV)">
            <setenv name="STREAM_LEVEL" value="${1}" type="temp"/>
         </match>
         <match pattern="(SIT)">
            <setenv name="STREAM_LEVEL" value="${1}" type="temp"/>
         </match>
         <match pattern="(UAT)">
            <setenv name="STREAM_LEVEL" value="${1}" type="temp"/>
         </match>
      </resultsblock>
   </command>
   
   <command name="autobl">
      <execute>
         ${BF_ROOT}autobl.pl --bftag "$1" --srcstream "$2" --bfroot "$3" --bldev $4 --blsit $5 --bluat $6
         #print "LOCAL - NO REBASE NEEDED"
      </execute>
      <resultsblock>
         <match pattern="^([A-Z]+)_OLDBL=(.+)$">
            <bom category="build_report" section="baselines">
               <field name="testlvl" text="$1"/>
               <field name="oldbl" text="$2"/>
            </bom>
            <setenv name="testlvl" value="$1"/>
            <setenv name="OLDBL" value="$2" type="temp"/>
         </match>      
         <match pattern="^([A-Z]+)_NEWBL=(.+)$">
            <bom category="build_report" section="baselines">
               <field name="newbl" text="$2"/>
            </bom>
            <setenv name="testlvl" value="$1"/>
            <setenv name="NEWBL" value="$2" type="temp"/>
            <setenv group="[ADAPTOR]" name="BL_${VIEW_NAME}" value="$2"/>
         </match>
         <match pattern="^LOCAL - NO REBASE NEEDED$">
            <field name="testlvl" text="LOCAL"/>
            <setenv name="DO_REBASE" value="NO"/>
         </match>
         <match pattern="^(\w+\ MUST\ BE\ REBASED\ BEFORE\ \w+)$">
            <setenv name="errors" value="$1\n" type="temp append\n"/>
            <setenv name="DO_REBASE" value="NO"/>
            <bom category="error_report" section="errors">
               <field name="error" text="$1"/>
            </bom>
         </match>
         <match pattern="^(NO REBASE NEEDED)$">
			   <setenv name="errors" value="$1\n" type="temp append\n"/>
            <setenv name="DO_REBASE" value="NO"/>
            <bom category="error_report" section="errors">
               <field name="error" text="$1"/>
            </bom>
         </match>
         <match pattern="(Not ownercleartool)">
			   <setenv name="errors" value="$1\n" type="temp append\n"/>
            <setenv name="DO_REBASE" value="NO"/>
            <bom category="error_report" section="errors">
               <field name="error" text="$1"/>
            </bom>
         </match>
         <match pattern="^(RC=.*)$">
			   <setenv name="errors" value="$1\n" type="temp append\n"/>
            <setenv name="DO_REBASE" value="NO"/>
            <bom category="error_report" section="errors">
               <field name="error" text="$1"/>
            </bom>
         </match>
         <match pattern="^(The view.+does not exist!)$">
			   <setenv name="errors" value="$1\n" type="temp append\n"/>
            <setenv name="DO_REBASE" value="NO"/>
            <bom category="error_report" section="errors">
               <field name="error" text="$1"/>
            </bom>
         </match>
         <match pattern="^(\d)$">
            <setenv name="errors" value="$1\n" type="temp append\n"/>
            <setenv name="DO_REBASE" value="NO"/>
            <bom category="error_report" section="errors">
               <field name="error" text="$1"/>
            </bom>
         </match>
      </resultsblock>
   </command>
   <!-- 
      This command lists the activities that occurred between two baselines, 
		it then calls cc_actdescribe to gather further details about the activities -->
	<command name="cc_baselineactivities">
		<execute>
         cd $VIEW_NAME
         cleartool diffbl -act $1@\$4 $2@\$4
		</execute>
		<resultsblock>
			<match pattern="^[->]>\s+([^\s].*?)\s.*$">
				<run command="cc_actdescribe" params="$VIEW_NAME $1" server="$BF_SERVER" dir="/" timeout="360"/>
			</match>
         <match pattern="^Source Stream is LOCAL .+$">
            <setenv name="Changes" value="$_" type="temp"/>
         </match>
		</resultsblock>
	</command>
	<!-- This command gathers details about an activity and logs pertinent information to the BuildForge BOM -->
	<command name="cc_actdescribe">
		<execute>
         cd $1
         cleartool lsact -l $2
		</execute>
		<resultsblock>
			<!-- look for something resempling an activity identifier -->
			<match pattern="^activity\s&quot;(.*?)&quot;$">
				<bom category="Source" section="activities">
					<field name="id" text="$1"/>
				</bom>
			</match>
			<!-- look for some stream information -->
			<match pattern="stream:\s(.*?)$">
				<bom category="Source" section="activities">
					<field name="stream" text="$1"/>
				</bom>
			</match>
			<!-- See if we get a title for this activity -->
			<match pattern="title:\s(.*?)$">
				<bom category="Source" section="activities">
					<field name="title" text="$1"/>
				</bom>
			</match>
		</resultsblock>
	</command>
	
	<!-- The bomformat sets up the BuildForge BOM display for the information we gather during this interface execution -->
	<!-- A category is a top level expandable item -->
	<bomformat category="Source" title="Source Changes">
		<!-- A section defines the columns for blocks of information, a new row of information is added 
			each time the last field (by order number) in a block is populated with new information -->
		<section name="changes">
			<field order="1" name="file" title="File/Dir Name"/>
			<field order="2" name="version" title="Version"/>
			<field order="3" name="date" title="Date"/>
			<field order="4" name="user" title="User"/>
			<field order="5" name="comment" title="Comment"/>
		</section>
		<section name="activities">
			<field order="1" name="id" title="Activity"/>
			<field order="3" name="stream" title="Stream"/>
			<field order="4" name="title" title="Title"/>
		</section>
		<section name="changeset">
			<field order="1" name="version" title="Change set version"/>
		</section>
	</bomformat>
   <bomformat category="build_report" title="Baseline Report">
      <section name="baselines">
         <field order="1" name="testlvl" title="Test Level"/>
         <field order="2" name="oldbl" title="Old Baseline"/>
         <field order="3" name="newbl" title="New Baseline"/>
      </section>
   </bomformat>
   <bomformat category="error_report" title="Baseline Errors">
      <section name="errors">
         <field order="1" name="error" title="Errors"/>
      </section>
   </bomformat>
   
   
</PROJECT_INTERFACE>

=== greenscar/scripts/buildforge/ClearQuestBaseClearCaseByDate.xml
<?xml version="1.0"?>
<!-- (c) Copyright by IBM Corp. and other(s) [2003], 2007 All Rights Reserved. -->
<!DOCTYPE PROJECT_INTERFACE SYSTEM "interface.dtd">
<PROJECT_INTERFACE IFTYPE="Defect" INSTANCE="7.021">
	<template>
		<!-- Template section, these are parsed out of the final xml and used to populate an 
		existing environment group if an instance of this interface is linked with a project.
		However, use the list below to help identify the variables needed to run this interface
		if you are integrating it during a regular BuildForge step.
		-->
		<env name="CurDate" value=".date %d-%b-%y.%H:%M:%S"/>
		<env name="LAST_RUN" value="1-Jan-05.00:00:00"/>
		<env name="VIEW" value="my_interface_view"/>
		<env name="VOB_PATH" value="\AdaptorVob"/>
		<env name="CQ_USER" value="admin"/>
		<env name="CQ_PASSWORD" value=""/>
		<env name="BFSERVER" value="BFServerName"/>
		<env name="UNIXCLIENT" value="0"/>
		<env name="_CHAR_NATIVE" value="1" />
	</template>
	<!-- The ClearCaseByDate entry point is used to identify clearquest records that have been associated with 
	clearcase changes since the last run of this particular instance of the interface -->
	<interface>
		<!-- In this interface, 'Resolving' and 'Erroring' are two templates that will be used to construct an email post-build -->
		<setenv name="Resolving" value="- ClearQuest Defect Records associated with this build -\n" type="temp"/>
		<setenv name="Erroring" value="\n- The following errors occurred while interacting with ClearQuest -\n" type="temp"/>

		<!-- Set some platform specific information -->
		<setenv name="CdCommand" value="cd /view" type="temp" condition="true($UNIXCLIENT==1)"/>
		<setenv name="CdCommand" value="pushd \\view" type="temp" condition="true($UNIXCLIENT==0)"/>
		<setenv name="DirSep" value="/" type="temp" condition="true($UNIXCLIENT==1)"/>
		<setenv name="DirSep" value="\" type="temp" condition="true($UNIXCLIENT==0)"/>
		
		<!-- MyChanges is the start of the list of users to be emailed with change information -->
		<adduser group="MyChangers" user="cmadmins@mycompany.com"/>
		<!-- cc_cq_changes is the initial command that will query clearcase for 
			clearquest defect information, and modify the defect -->
		<run command="cc_cq_changes" params="$LAST_RUN $VIEW $VOB_PATH" server="$BFSERVER" dir="/" timeout="360"/>
		<!-- Here we test to see if we have any errors, 'Errors' should have some data if an error was found -->
		<ontempenv name="Errors" state="hastext">
			<step result="FAIL"/>
		</ontempenv>
		<!-- If there were no errors, then update our environment for the next run -->
		<onstep result="pass">
			<setenv group="[ADAPTOR]" name="LAST_RUN" value="$CurDate"/>
		</onstep>
		<!-- Set some notifications for when the build completes -->
		<onproject result="fail">
			<notify group="MyChangers" subject="Build $BF_TAG ($CurDate) Failed." message="${Resolving}${Resolved}${Erroring}${Errors}"/>
		</onproject>
		<onproject result="pass">
			<notify group="MyChangers" subject="Build $BF_TAG ($CurDate) Passed." message="${Resolving}${Resolved}"/>
		</onproject>
	</interface>
	<!-- Searches the view location for any base cc/cq integrated records (CrmRequest type hyperlinks) -->
	<command name="cc_cq_changes">
		<execute>
cleartool startview $2
$CdCommand${DirSep}$2 &amp;&amp; cleartool find .$3 -all -cview -version "hltype(CrmRequest) &amp;&amp; created_since($1)" -print
		</execute>
		<resultsblock>
			<match pattern="^(.*?)(\@\@.*?\d+)$">
				<bom category="ClearQuest" section="text">
					<field name="File" text="$1"/>
				</bom>
				<run command="cq_getcrm" params="$VIEW ${1}${2}" server="$BFSERVER" dir="/" timeout="360"/>
			</match>
		</resultsblock>
	</command>
	<!-- Gathers more information on the ClearQuest hyperlink -->
	<command name="cq_getcrm">
		<execute>
$CdCommand${DirSep}$1 &amp;&amp; cleartool describe -long -ahlink CrmRequest $2
		</execute>
		<resultsblock>
			<match pattern="^\s+CrmRequest\@.*&quot;(.*?)([0-9]+)&quot;$">
				<bom category="ClearQuest" section="text">
					<field name="Defect" text="${1}${2}"/>
				</bom>
				<bom category="ClearQuest" section="resolve_status">
					<field name="Defect" text="${1}${2}"/>
				</bom>
				<run command="cq_resolve" params="$1 ${1}${2}" server="" dir="/"/>
			</match>
		</resultsblock>
	</command>
	<!-- Executes the integration script 'cq_resolve' to resolve defects in ClearQuest -->
	<command name="cq_resolve">
		<integrate>
cqperl bfcqresolve.pl $2 Fixed "Fixed in build $BF_TAG"
		</integrate>
		<resultsblock>
			<resultsblock beginpattern="^ERROR:">
				<match pattern="^(.*?)$">
					<bom category="CQErrors" section="text">
						<field name="Error" text="$1"/>
					</bom>
					<setenv name="Errors" value="$1\n" type="temp append\n"/>
				</match>
			</resultsblock>
			<resultsblock beginpattern="^(?!ERROR:).+">
				<match pattern="^(.*?)$">
					<bom category="ClearQuest" section="resolve_status">
						<field name="Status" text="$1"/>
					</bom>
					<setenv name="Resolved" value="$1\n" type="temp append\n"/>
				</match>
			</resultsblock>
		</resultsblock>
	</command>
	<!-- The bomformat sets up the BuildForge BOM display for the information we gather during this interface execution -->
	<!-- A category is a top level expandable item -->
	<bomformat category="ClearQuest" title="ClearQuest Defect Information">
		<!-- A section defines the columns for blocks of information, a new row of information is added 
			each time the last field (by order number) in a block is populated with new information -->
		<section name="text">
			<field order="1" name="File" title="Vob Object"/>
			<field order="2" name="Defect" title="Defect Id"/>
		</section>
		<section name="ucm">
			<field order="1" name="File" title="Vob Object"/>
			<field order="2" name="Defect" title="Activity/Defect Id"/>
		</section>
		<section name="resolve_status">
			<field order="1" name="Defect" title="Defect Id"/>
			<field order="2" name="Status" title="Status"/>
		</section>
	</bomformat>
	<bomformat category="CQErrors" title="ClearQuest Interaction Errors">
		<section name="text">
			<field order="1" name="Error" title="Error Details"/>
		</section>
	</bomformat>
</PROJECT_INTERFACE>

=== greenscar/scripts/buildforge/bom_and_env_var_test.xml
<!DOCTYPE PROJECT_INTERFACE SYSTEM "interface.dtd">
<PROJECT_INTERFACE IFTYPE="Source" INSTANCE="7.02">
   <template>  
      <env name="COLOR" value="Red-Green" />  
      <env name="SIZE" value="Small" />  
      <env name="BF_SERVER" value="ball" />  
   </template>  
   
   <interface>
      <run command="determine_color" params="$COLOR" server="$BF_SERVER" dir="/" timeout="360" />  
      
      <adduser group="BALL_WATCHERS" user="${BF_USER_EMAIL}"/>
      
      <ontempenv name="Changed" state="empty">  
         <step result="fail"/>  
      </ontempenv>  
      <onproject result="fail">  
         <notify group="BALL_WATCHERS" subject="Build failed!" message="The $SIZE $COLOR ball failed!" />  
      </onproject>  
   </interface>
   
   <command name="determine_color">  
      <execute>  
         echo $1  
      </execute>  
      <resultsblock>  
         <match pattern="(.*)?-(.*)?">  
            <bom category="ball_category" section="ball_section">  
               <field name="color" text="${1}"/>  
               <field name="date" text="$2"/>  
            </bom>  
            <setenv group="[ADAPTOR]" name="COLOR1" value="$1"/>
            <setenv group="[ADAPTOR]" name="COLOR2" value="$2"/>
            <setenv name="Changed" value="TRUE" type="temp"/>  
         </match>  
      </resultsblock>  
   </command>  
   
   <bomformat category="ball_category" title="Ball Category">  
      <section name="ball_section">  
         <field order="1" name="color" title="Color"/>  
         <field order="2" name="date" title="Current Date"/>  
      </section>  
   </bomformat>
</PROJECT_INTERFACE>

=== greenscar/scripts/buildforge/qc_update_rev2.xml
<!DOCTYPE PROJECT_INTERFACE SYSTEM "interface.dtd">
<PROJECT_INTERFACE IFTYPE="Source" INSTANCE="7.02">
   <template>
      <!-- Template section, these are parsed out of the final xml and used to populate an 
      existing environment group if an instance of this interface is linked with a project.
      However, use the list below to help identify the variables needed to run this interface
      if you are integrating it during a regular BuildForge step.
      -->
      <env name="BF_SERVER"   value="iedaau020_wasadmin"/>
      <env name="TEST_APP"    value=""/>
      <env name="OLD_STATUS"    value=""/>
      <env name="NEW_STATUS"    value=""/>
   </template>
   
   <interface>
      <run command="clean_system_outs" params="$TEST_APP" server="$BF_SERVER" timeout="600"/>
   </interface>
   
   <command name="clean_system_outs">
      <execute>
         C:\WINDOWS\system32\cscript.exe D:\BFAgent\QCDefectUpdate\StatusUpdate.vbs "$TEST_APP" "$OLD_STATUS" "$NEW_STATUS"
      </execute>
      <resultsblock>
         <match pattern="((\d+,\s?)+)">
            <bom category="defects" section="IDS">
               <field name="id" text="$1"/>
            </bom>
         </match>
      </resultsblock>
   </command>   
   
   <bomformat category="defects" title="Defect Fixes Included in Build">
      <section name="IDS" expandable="true">
         <field order="1" name="id" title="QC Defect Num"/>         
      </section>
   </bomformat>
</PROJECT_INTERFACE>

=== greenscar/scripts/buildforge/autobl_oo.xml
<!DOCTYPE PROJECT_INTERFACE SYSTEM "interface.dtd">
<PROJECT_INTERFACE IFTYPE="Source" INSTANCE="7.02">
   <template>
      <env name="VIEW_NAME"     value="STP_75.0.0.0_DEV"/>
      <env name="PVOB"              value="DC_Projects"/>
      <env name="BF_SERVER"         value="iedaau020"/>
      <env name="BF_ROOT"           value="/home/wasadmin"/>
      <env name="BF_USER_EMAIL"     value="james.sandlin@hhsc.state.tx.us"/>
		<env name="CUR_DATE"          value="required" />
      <env name="DO_REBASE"         value="YES"/>
   </template>
   
   <interface>      
		<adduser group="MyChangers" user="james.sandlin@hhsc.state.tx.us"/>
      <!--
      <adduser group="MyChangers" user="Raghurajan.Gurunathan@hhsc.state.tx.us"/>
      -->
      <adduser group="MyChangers" user="${BF_USER}"/>
      
      <setenv name="NEWBL" value="" type="temp"/>
      <setenv name="qcnums" value="" type="temp"/>
      
      <run command="autobl" params="$B $VIEW_NAME" server="$BF_SERVER" dir="/autobl" timeout="600"/>
      
      <run command="setqcperms" server="$BF_SERVER" dir="/autobl" timeout="600"/>
      
      <ontempenv name="errors" state="hastext">
			<step result="fail"/>
		</ontempenv>
      
      
		<onproject result="fail">
			<notify group="MyChangers" subject="Build $BF_TAG ($CurDate) Failed." message="${errors}"/>
		</onproject>
      
      
   </interface>
   
   <command name="check_test_lvl">
      <execute>
         echo '$1'
      </execute>
      <resultsblock>
         <match pattern="(LOCAL)">
            <setenv name="DO_REBASE" value="NO" type="temp"/>
         </match>
      </resultsblock>
   </command>
   
   <command name="setqcperms">
      <execute>
         echo $qcnums
      </execute>
      <resultsblock>
         <match pattern="or (.*) or">
            <setenv name="qclist" value="$1"/>
         </match
         <match pattern="or (.*)">
            <setenv name="qclist" value="$1"/>
         </match>
      </resultsblock>
   </command>
   
   <command name="autobl">
      <execute>
         cd ${BF_ROOT}HHSC_Ratdoc_Int/HHSC_Ratdoc/build_and_deploy/scripts/autobl
         cqperl autobloo.pl
         #cd /home/wasadmin/autobl
         #cqperl test.pl
      </execute>
      <resultsblock>
         <match pattern="^release_num=(.*)\^itg_num=(.*)\^qc_num=(.*)\^team=(.*)\^actid=(.*)\^ucm_stream=(.*)\^timestamp=(.*)\^owner=(.*)\^headline=(.*)$">
            <bom category="report" section="activities">
               <field name="releasenum" text="$1"/>
               <field name="itgnum" text="$2"/>
               <field name="qcnum" text="$3"/>
               <field name="team" text="$4"/>
               <field name="actid" text="$5"/>
               <field name="stream" text="$6"/>
               <field name="timestamp" text="$7"/>
               <field name="owner" text="$8"/>
               <field name="headline" text="$9"/>
            </bom>
            <setenv name="qcnums" value="$3" type="temp append or "/>
         </match>
         <match pattern="^OLDBL=(.+)\^NEWBL=((.+?)\^)(.*)release_num=(.*)\^itg_num=(.*)\^qc_num=(.*)\^team=(.*)\^actid=(.*)\^ucm_stream=(.*)\^timestamp=(.*)\^owner=(.*)\^headline=(.*)$">
            <setenv name="OLDBL" value="$1" type="temp"/>
            <setenv name="NEWBL" value="$3" type="temp"/>
            <bom category="baselines" section="baselines">
               <field name="oldbl" text="$1"/>
               <field name="newbl" text="$3"/>
            </bom>
            <bom category="report" section="activities">
               <field name="releasenum" text="$5"/>
               <field name="itgnum" text="$6"/>
               <field name="qcnum" text="$7"/>
               <field name="team" text="$8"/>
               <field name="actid" text="$9"/>
               <field name="stream" text="$10"/>
               <field name="timestamp" text="$11"/>
               <field name="owner" text="$12"/>
               <field name="headline" text="$13"/>
            </bom>
            <setenv name="qcnums" value="$7" type="temp append or "/>
            <setenv name="newbl" value="$1"/>
            <setenv name="oldbl" value="$3"/>
            <!--
            <run command="loadactdetails" params="$4" server="$BF_SERVER" dir="/autobl" timeout="600"/>
            -->
         </match>
         <!--
         <match pattern="^OLDBL=(.+)\^NEWBL=((.+?)\^)">
            <setenv name="OLDBL" value="$1"/>
            <setenv name="NEWBL" value="$2" type="temp"/>
            <bom category="baselines" section="baselines">
               <field name="oldbl" text="$1"/>
               <field name="newbl" text="$3"/>
            </bom>
            <setenv name="newbl" value="$1"/>
            <setenv name="oldbl" value="$2"/>
         </match>      
         <match pattern="^LOCAL - NO REBASE NEEDED$">
            <field name="testlvl" text="LOCAL"/>
            <setenv name="DO_REBASE" value="NO"/>
         </match>
         <match pattern="^(ERROR:.*)">
            <setenv name="errors" value="$1\n" type="temp append\n"/>
            <setenv name="DO_REBASE" value="NO"/>
            <bom category="error_report" section="errors">
               <field name="error" text="$1"/>
            </bom>
         </match>
         -->
         <match pattern="^(WARNING:.*)">
            <!--
			   <setenv name="errors" value="$1\n" type="temp append\n"/>
            -->
            <setenv name="DO_REBASE" value="NO"/>
            <bom category="error_report" section="errors">
               <field name="error" text="$1"/>
            </bom>
         </match>
      </resultsblock>
   </command>
	<!-- The bomformat sets up the BuildForge BOM display for the information we gather during this interface execution -->
	<!-- A category is a top level expandable item -->
	<bomformat category="report" title="Source Changes">
		<!-- A section defines the columns for blocks of information, a new row of information is added 
			each time the last field (by order number) in a block is populated with new information -->
		<section name="activities">
         <field order="1" name="releasenum" title="Release Num"/>
         <field order="2" name="itgnum" title="ITG Num"/>
         <field order="3" name="qcnum" title="QC Num"/>
         <field order="4" name="team" title="Team"/>
			<field order="5" name="actid" title="CQ ID"/>
			<field order="6" name="stream" title="Stream"/>
			<field order="7" name="timestamp" title="Timestamp"/>
			<field order="8" name="project" title="CC Project"/>
         <field order="10" name="owner" title="Owner"/>
         <field order="11" name="headline" title="Headline"/>
		</section>
   </bomformat>
   <bomformat category="baselines" title="Baseline Report">
      <section name="baselines">
         <field order="1" name="oldbl" title="Old BL"/>
         <field order="2" name="newbl" title="New BL"/>
      </section>
   </bomformat>
</PROJECT_INTERFACE>
